/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teamproject.myapp;

import teamproject.myapp.menu.MainMenu;
import teamproject.util.Prompt;

public class App {

    public static void main(String[] args) {
        Prompt prompt = new Prompt(System.in);
        new MainMenu(prompt).execute();
        prompt.close();
    }
}
