package project;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import jeonghuijun.project.handler.customer.CustomerAddHandler;
import jeonghuijun.project.handler.customer.CustomerDeleteHandler;
import jeonghuijun.project.handler.customer.CustomerListHandler;
import jeonghuijun.project.handler.customer.CustomerModifyHandler;
import jeonghuijun.project.handler.customer.CustomerViewHandler;
import jeonghuijun.project.dao.mysql.CustomerDaoImpl;
import jeonghuijun.project.dao.CustomerDao;
import java.sql.Connection;
import java.sql.DriverManager;
import jeonghuijun.menu.MenuGroup;
import jeonghuijun.project.handler.reservation.ReservationAddHandler;
import jeonghuijun.project.handler.reservation.ReservationDeleteHandler;
import jeonghuijun.project.handler.reservation.ReservationListHandler;
import jeonghuijun.project.handler.reservation.ReservationModifyHandler;
import jeonghuijun.project.handler.reservation.ReservationViewHandler;
import jeonghuijun.project.dao.ReservationDao;
import jeonghuijun.project.dao.mysql.ReservationDaoImpl;

import jeonghuijun.util.Prompt;

public class App {

    Prompt prompt = new Prompt(System.in);

    //List<Member> memberRepository = new ArrayList<>();

    CustomerDao customerDao;

    ReservationDao reservationDao;

    MenuGroup mainMenu;

//  Socket socket;
//  DataInputStream in;
//  DataOutputStream out;

    App() {
//    prepareNetwork();
        prepareDatabase();
        prepareMenu();
    }

    public static void main(String[] args) {
        System.out.println("[고객관리 시스템]");

        new App().run();
    }

    void prepareDatabase() {
        try {

            Connection con = DriverManager.getConnection(
//          "jdbc:mysql://localhost/studydb", "study", "1111");
                "jdbc:mysql://db-ld29t-kr.vpc-pub-cdb.ntruss.com/studydb", "study", "Bitcamp!@#123");

            customerDao = new CustomerDaoImpl(con);
            reservationDao = new ReservationDaoImpl(con);

        } catch (Exception e) {
            System.out.println("통신 오류!");
            e.printStackTrace();
        }
    }

    void prepareMenu() {
        mainMenu = MenuGroup.getInstance("메인");

        MenuGroup customerMenu = mainMenu.addGroup("고객정보");
        customerMenu.addItem("등록", new CustomerAddHandler(customerDao, prompt));
        customerMenu.addItem("조회", new CustomerViewHandler(customerDao, prompt));
        customerMenu.addItem("변경", new CustomerModifyHandler(customerDao, prompt));
        customerMenu.addItem("삭제", new CustomerDeleteHandler(customerDao, prompt));
        customerMenu.addItem("목록", new CustomerListHandler(customerDao, prompt));

        MenuGroup reservationMenu = mainMenu.addGroup("예약정보");
        reservationMenu.addItem("등록", new ReservationAddHandler(reservationDao, prompt));
        reservationMenu.addItem("조회", new ReservationViewHandler(reservationDao, prompt));
        reservationMenu.addItem("변경", new ReservationModifyHandler(reservationDao, prompt));
        reservationMenu.addItem("삭제", new ReservationDeleteHandler(reservationDao, prompt));
        reservationMenu.addItem("목록", new ReservationListHandler(reservationDao, prompt));


    }

    void run() {
        while (true) {
            try {
                mainMenu.execute(prompt);
                prompt.close();
//        close();
                break;
            } catch (Exception e) {
                System.out.println("예외 발생!");
            }
        }
    }

//  void close() {
//    try (Socket socket = this.socket;
//      DataInputStream in = this.in;
//      DataOutputStream out = this.out;) {
//
//      out.writeUTF("quit");
//      System.out.println(in.readUTF());
//
//    } catch (Exception e) {
//      // 서버와 연결을 끊는 과정에서 예외가 발생한 경우 무시한다.
//      // 왜? 따로 처리할 것이 없다.
//    }
//  }
}
