/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teamproject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        String ANSI_CLEAR = "\033[0m";
        String ANSI_BOLD_RED = "\033[1;31m";
        String ANSI_RED = "\033[0m;31m";
        String appTitle = "[과제관리 시스템]";

        String menu1 = "1.후기게시판",
            menu2 = "2.모집게시판",
            menu3 = "3.계획게시판",
            menu4 = "4.마이페이지",
            menu5 = "5.추천게시판",
            menu6 = "6.종료";

        System.out.println(ANSI_BOLD_RED + appTitle + ANSI_CLEAR);
        System.out.println();
        System.out.println(menu1);
        System.out.println(menu2);
        System.out.println(menu3);
        System.out.println(menu4);
        System.out.println(menu5);
        System.out.println(menu6);
    }
}
